---
- name: Caluculate memory
  ansible.builtin.command: dd if=/dev/zero of=/swap bs=1M count=1024

- name: Check whether swap file is created
  ansible.builtin.command: dd if=/dev/zero of=/swap bs=1M count=1024

- name: Copy the file to be used for swap
  ansible.builtin.command: dd if=/dev/zero of=/swap bs=1M count=1024

- name: Format the file for swap
  ansible.builtin.command: mkswap /swap

- name: Add the file to the system as a swap file
  ansible.builtin.command: swapon /swap
