---
name: build
on: [deployment, push]

jobs:
  ansible-lint:
    uses: github-actions-reusable-workflows/ansible-lint/.github/workflows/workflows.yml@main

  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Yelp detect-secrets
        run: |
          pip install detect-secrets

      - name: Execulte detect-secrets(disabled KeywordDetector plugin)
        run: |
          detect-secrets scan --disable-plugin KeywordDetector \
          | jq .results > results.json

      - name: Check whether detect-secrets found vulnerability
        run: |
          line=$(cat results.json | wc -w)
          if [ $line -gt 2 ]; then
            echo "vulnerability was found"
            detect-secrets scan | jq .results -C
            exit 1;
          fi

      - name: Show detect-secrets version
        run: |
          pip list | grep detect-secrets \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'detect-secrets.* '

  vm-centos7:
    uses: github-actions-reusable-workflows/molecule-ec2/.github/workflows/workflows.yml@main
    with:
      ami-name: centos7-1*
      molecule-instance-type: t2.small
      pip-requirements-file: molecule/requirements.txt
      python-interpreter: /usr/bin/python
      tag-prefix: molecule_swap_centos7
    secrets:
      AMI_OWNER_ID: ${{ secrets.AMI_OWNER_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VPC_SUBNET_ID: ${{ secrets.VPC_SUBNET_ID }}

  vm-centos-stream8:
    uses: github-actions-reusable-workflows/molecule-ec2/.github/workflows/workflows.yml@main
    with:
      ami-name: centos-stream8-*
      molecule-instance-type: t4g.small
      pip-requirements-file: molecule/requirements.txt
      python-interpreter: /usr/libexec/platform-python
      tag-prefix: molecule_swap_centos-stream8
    secrets:
      AMI_OWNER_ID: ${{ secrets.AMI_OWNER_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VPC_SUBNET_ID: ${{ secrets.VPC_SUBNET_ID }}

  trailing-whitespace:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/find-trailing-whitespace@master

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute yamllint
        run: yamllint *

      - name: Show yamllint version
        run: |
          yamllint --version \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'yamllint.* '
